export const aboutDatos = {
  titulo: "Quiénes somos",
  subtitulo1: "Metal, pasión, honestidad, corazón y fuego\nAsí ruge el corazón de Koba Live.",
  texto1: `Nuestra historia quizá no sea diferente a otras, pero la llevamos grabada a fuego. Sugaar Musika Elkartea es la fuerza que impulsa el Koba Live, un comando de metaleros que respira, vive y sangra música extrema. Desde el primer rugido, compartimos una misión: forjar un festival sin concesiones en nuestra tierra, donde clavamos nuestras raíces.\n\nHa sido una batalla constante, tallando a martillazos nuestro camino hasta que surgió la oportunidad de desatar todo el poder de Koba en Abadiño. El día que recibimos el respaldo para la primera edición quedó marcado en nuestra piel: uno de los momentos más electrizantes de nuestras vidas.\n\nEl equipo se formó como un ritual ancestral, el destino uniendo guerreros con un mismo objetivo. Aquí encontrarás almas de acero que dejan su esencia en cada detalle para que vivas una experiencia que arrasará tus sentidos.`,
  seccion: `Las palabras se las lleva el viento, pero el metal retumba en tus huesos.\nCada edición sellamos contigo un pacto de sangre:\nQue sientas el metal en su forma más salvaje, cruda y demoledora.\nTe esperamos en las tierras de Koba.`,
  texto2: `Nuestro territorio salvaje lo hace posible. La esencia del KOBA Live está en el imponente cresterío del Anboto y en la legendaria cueva de Mari. En ese santuario primitivo moraron Mari y Sugaar, un dragón-serpiente con poder de transformación humana, consorte de Mari, la poderosa deidad de la mitología vasca.\n\nCuando una banda conquista el escenario, Mari y Sugaar emergen de las sombras, fusionándose con cada riff desgarrador, cada grito visceral, cada golpe de batería que sacude las montañas. Dioses ancestrales, mitología brutal y naturaleza indómita se entrelazan con el metal para crear una experiencia que va más allá de lo musical, alcanzando lo ritual.\n\nEn Abadiño te aguarda la Koba Family y la mismísima diosa Mari, cabalgando las tormentas en su carro de fuego, con su melena salvaje ondeando a las puertas de su morada milenaria.`,
  pregunta: "¿Te atreves a formar parte de la leyenda?",
  subtitulo2: "Pulsa play y revive la potencia del Koba Live en este documental forjado en las tierras de Mari."
}
