import { bandasLogo } from '@imagenes/imagenes.js';
import resumenesBandas from './resumenesBandas2025.js';
import { bandasSpotifyUrls } from './bandasSpotify2025.js';

const bandasDatos2025 = [
  { // Asgarth
    nombre: 'Asgarth',
    imagen: bandasLogo.asgarthLogo,
    spotify: bandasSpotifyUrls.asgarth,
    estilo: 'Melodic Power Metal',
    origen: { pais: 'España', provincia: 'Gipuzkoa', ciudad: 'Donosti' },
    año: 1998,
    resumen: resumenesBandas.Asgarth,
    integrantes: {
      cantante: 'Asier Enbil',
      guitarra: ['Ander Cañas', 'Unai Zabala'],
      bajo: 'Mikel Yarza',
      bateria: 'Etxahun Urkizu',
    },
    albums: [
      { nombre: 'Asgarth Zuzenean', año: 2024 },
      { nombre: 'Zeldatik', año: 2021 },
      { nombre: 'Garrasia...', año: 2006 },
      { nombre: 'III', año: 2002 },
      { nombre: 'Etorkizunaren sustraia', año: 2000 },
      { nombre: 'Jainkoen egoitza', año: 1999 },
    ],
  },
  { // Before The Dawn
    nombre: 'Before The Dawn',
    imagen: bandasLogo.beforeTheDawnLogo,
    spotify: bandasSpotifyUrls.beforeTheDawn,
    estilo: 'Melodic Death Metal',
    origen: { pais: 'Finlandia', provincia: 'Päijänne Tavastia', ciudad: 'Nastola' },
    año: 1999,
    resumen: resumenesBandas.BeforeTheDawn,
    integrantes: {
      cantante: 'Paavo Laapotti',
      guitarra: ['Juho Räihä'],
      bajo: 'Pyry Hanski',
      bateria: 'Tuomas Saukonen',
    },
    albums: [
      { nombre: 'Stormbringers', año: 2023 },
      { nombre: 'Rise of the Phoenix', año: 2012 },
      { nombre: 'Deathstar Rising', año: 2011 },
      { nombre: 'Soundscape of Silence', año: 2008 },
      { nombre: 'Deadlight', año: 2007 },
      { nombre: 'The Ghost', año: 2006 },
      { nombre: '4:17 am', año: 2004 },
      { nombre: 'My Darkness', año: 2003 },
    ],
  },
  { // Eclipse
    nombre: 'Eclipse',
    imagen: bandasLogo.eclipseLogo,
    spotify: bandasSpotifyUrls.eclipse,
    estilo: 'Melodic Hard Rock',
    origen: { pais: 'Suecia', provincia: 'Estocolmo', ciudad: 'Estocolmo' },
    año: 1999,
    resumen: resumenesBandas.Eclipse,
    integrantes: {
      cantante: 'Erik Mårtensson',
      guitarra: ['Magnus Henriksson'],
      bajo: 'Victor Crusner',
      bateria: 'Philip Crusner',
    },
    albums: [
      { nombre: 'Megalomanium II', año: 2024 },
      { nombre: 'Megalomanium', año: 2023 },
      { nombre: 'Wired', año: 2021 },
      { nombre: 'Viva La Victoria', año: 2021 },
      { nombre: 'Paradigm', año: 2019 },
      { nombre: 'Monumentum', año: 2017 },
      { nombre: 'Armageddonize', año: 2015 },
      { nombre: 'Bleed & Scream', año: 2012 },
      { nombre: 'Are You Ready to Rock', año: 2008 },
      { nombre: 'Second to None', año: 2004 },
      { nombre: 'The Truth and a Little More', año: 2001 },
    ],
  },
  { // Ehun Kilo
    nombre: 'Ehun Kilo',
    imagen: bandasLogo.ehunKiloLogo,
    spotify: bandasSpotifyUrls.ehunKilo,
    estilo: 'Melodic Heavy Metal',
    origen: { pais: 'España', provincia: 'Gipuzkoa', ciudad: 'Elgoibar' },
    año: 1991,
    resumen: resumenesBandas.EhunKilo || '',
    integrantes: {
      cantante: 'Jon Zabala',
      guitarra: ['Jon Iturrino', 'Patxi Zabaleta'],
      bajo: 'Kristian Etxabe',
      bateria: 'Iñigo “Fiñi” Barrenetxea',
    },
    albums: [
      { nombre: 'Esaiek... Esaien', año: 1995 },
      { nombre: 'Euli artean', año: 1994 },
    ],
  },
  { // Moonshinerds
    nombre: 'Moonshinerds',
    imagen: bandasLogo.moonshinerdsLogo,
    spotify: bandasSpotifyUrls.moonshinerds,
    estilo: 'Melodic Hard Rock',
    origen: { pais: 'España', provincia: 'Bizkaia', ciudad: 'Durango' },
    año: 2009,
    resumen: resumenesBandas.Moonshinerds || '',
    integrantes: {
      cantante: 'Joseba Irigoras',
      guitarra: ['Joseba Irigoras', 'Jon Sánchez'],
      bajo: 'Liher Granados',
      bateria: 'Antonio Cantero',
    },
    albums: [
      { nombre: 'Moonshinerds', año: 2019 },
    ],
  },
  { // Suicidal Angels
    nombre: 'Suicidal Angels',
    imagen: bandasLogo.suicidalsAngelsLogo,
    spotify: bandasSpotifyUrls.suicidalAngels,
    estilo: 'Thrash Metal',
    origen: { pais: 'Grecia', provincia: 'Atica', ciudad: 'Atenas' },
    año: 2001,
    resumen: resumenesBandas.SuicidalAngels || '',
    integrantes: {
      cantante: 'Nick Melissourgos',
      guitarra: ['Nick Melissourgos'],
      bajo: 'Angel Lelikakis',
      bateria: 'Orfeas Tzortzopoulos',
    },
    albums: [
      { nombre: 'Profane Prayer', año: 2024 },
      { nombre: 'Years of Aggression', año: 2019 },
      { nombre: 'Division of Blood', año: 2016 },
      { nombre: 'Divide and Conquer', año: 2014 },
      { nombre: 'Bloodbath', año: 2012 },
      { nombre: 'Dead Again', año: 2010 },
      { nombre: 'Sanctify the Darkness', año: 2009 },
      { nombre: 'Eternal Domination', año: 2007 },
    ],
  },
  { // The Electric Alley
    nombre: 'The Electric Alley',
    imagen: bandasLogo.theElectricAlleyLogo,
    spotify: bandasSpotifyUrls.theElectricAlley,
    estilo: '',
    origen: { pais: '', provincia: '', ciudad: '' },
    año: null,
    resumen: resumenesBandas.TheElectricAlley || '',
    integrantes: {
      cantante: '',
      guitarra: '',
      bajo: '',
      bateria: '',
    },
    albums: [
      { nombre: '', año: null },
      { nombre: '', año: null },
    ],
  },
  { // Wolfheart 
    nombre: 'Wolfheart ',
    imagen: bandasLogo.wolfhearthLogo,
    spotify: bandasSpotifyUrls.wolfheart,
    estilo: '',
    origen: { pais: '', provincia: '', ciudad: '' },
    año: null,
    resumen: resumenesBandas.WolfheartAngels || '',
    integrantes: {
      cantante: '',
      guitarra: '',
      bajo: '',
      bateria: '',
    },
    albums: [
      { nombre: '', año: null },
      { nombre: '', año: null },
    ],
  },
];

export default bandasDatos2025;
