const resumenesBandas = {
  Asgarth: `Asgarth, fundada en 1997 en Añorga (San Sebastián), debutó en 1999 con "La residencia de los dioses", logrando reconocimiento en concursos como el IX Concurso de Maquetas de Euskadi. Tras firmar con IZ, presentaron su primer álbum en la Feria del Libro y Disco Vasco de Durango. Su segundo disco, "La raíz del futuro", consolidó su éxito con más de 60 conciertos entre 2000 y 2001. En 2002 lanzaron "III", mostrando un sonido más maduro, pero la bajada de interés por el heavy metal llevó a la banda a un parón. En 2004, Iban Fernández sustituyó a Unai Corral y en 2005 grabaron "Gritar", de estilo más rockero. Tras una década de trayectoria, se despidieron en 2007. En 2020 anunciaron su regreso, aunque la pandemia retrasó su concierto de retorno hasta mayo de 2022 en Añorga. Ese mismo año publicaron el álbum "Zeldatik".`,
  BeforeTheDawn: `Before The Dawn fue fundada en 1999 por Tuomas Saukkonen como su proyecto en solitario. Tras grabar sus primeras demostraciones, reclutó músicos para actuar en vivo. En 2003, junto a Panu Willman, Mike Ojala y Kimmo Nurmi, lanzaron su primer álbum "Mi oscuridad", seguido por "4:17 am" en 2004.\nEn 2005, Saukkonen renovó completamente la alineación, incorporando a Lars Eikind en voces y bajo, y a Juho Räihä en guitarra. La banda lanzó "El fantasma" en 2006, seguido por "Ventana" en 2007, cuyo sencillo "Deadsong" alcanzó el #2 en las listas finlandesas.\nDurante las grabaciones del álbum "Paisaje sonoro de silencio" en 2008, la banda experimentó más cambios de formación, incorporando posteriormente al baterista Atte Palokangas. En 2010 lanzaron el EP "Década de la oscuridad" que alcanzó el #1 en Finlandia, mientras que "Deathstar Rising" (2011) llegó al #8.\nEn enero de 2013, Saukkonen anunció el fin de Before The Dawn para centrarse en un nuevo proyecto llamado "Wolfheart". Tras ocho años de silencio, la banda regresó en 2021 con el sencillo "The Final Storm", y en 2022 incorporó a Paavo Laapotti como vocalista. En 2023 lanzaron el álbum "Tormenta", y en febrero de 2024 anunciaron un nuevo EP titulado "Llama arcaica".`,
  Eclipse: `Eclipse es una banda sueca de hard rock formada en Estocolmo en 1999. La formación actual incluye a Erik Mårtensson como vocalista, Magnus Henriksson en la guitarra, Philip Crusner en la batería y Victor Crusner en el bajo. El grupo fue fundado por Mårtensson junto al batería y teclista Anders Berlin, y pronto se unió Henriksson. Consiguieron su primer contrato discográfico con el sello inglés Z Records, lanzando su álbum debut "The Truth and a Little More" en 2001.\nPosteriormente, Eclipse firmó con el sello italiano Frontiers Records y publicó "Second To None" en 2004. En 2008 lanzaron "Are You Ready to Rock", consolidando su presencia en la escena del hard rock melódico. Mårtensson también participó en el proyecto paralelo W.E.T., que ganó notoriedad en el género.\nEn 2012, la banda publicó "Bleed & Scream", cuyo tema principal fue su primer sencillo y videoclip oficial, entrando en las listas suecas.\nEn 2015 lanzaron "Armageddonize", y participaron en el Melodifestivalen 2016 con la canción "Runaways". Aunque no avanzaron en la competición, ganaron visibilidad nacional.\nEn 2017 publicaron "Monumentum" y realizaron una gira europea, actuando en festivales destacados y consolidando su reputación internacional como una de las bandas más sólidas del hard rock contemporáneo.`,
  EhunKilo: `Ehun Kilo es una banda mítica de heavy metal melódico originaria de Elgoibar, Gipuzkoa, formada en 1991. Junto a Su Ta Gar, fueron pioneros en introducir el euskera en el heavy metal, contribuyendo de manera decisiva a la escena vasca con un estilo propio. Publicaron dos álbumes: ‘Euli Artean’ (Oihuka, 1993) y ‘Esaiek…’ (Oihuka, 1995), ambos caracterizados por potentes melodías, riffs pesados y letras en euskera que abordan temas diversos. Tras una intensa actividad en directo y una notable acogida entre los aficionados al heavy, la banda se disolvió en octubre de 1997 tras un último concierto en el Gaztetxe de Elgoibar.\nEn 2017, veinte años después de su separación, Ehun Kilo regresó a los escenarios invitados por el festival Hatortxu Rock, recuperando su formación original y participando en varios eventos destacados como Vértigo Rock (2022) y junto a Su Ta Gar en Eibar (2023). Su legado se mantiene como referente del heavy metal en euskera, siendo recordados por su experimentación musical y su aportación a la consolidación del género en Euskal Herria.`,
  // ...existing code...
};

export default resumenesBandas;
