const resumenesBandas = {
  Asgarth: `Asgarth fue una banda de metal melódico en euskera originaria del País Vasco, activa principalmente entre 1995 y 2004.\n\nCon una propuesta sonora que fusionaba metal melódico, rock progresivo y tintes atmosféricos, Asgarth se convirtió en un referente del metal en lengua vasca.\n\nSus letras, profundamente poéticas y emocionales, trataban temas como la identidad, la naturaleza, la mitología vasca y la introspección, lo que les permitió conectar de forma única con su público.\n\nLa banda publicó varios discos destacados como Izena Izana Da y Argiaren Hautsa, que fueron aclamados por su calidad musical y profundidad lírica.\n\nCon una cuidada producción y una puesta en escena intensa, sus directos eran experiencias envolventes que reflejaban su compromiso artístico y cultural.\n\nAunque se disolvieron en 2004, su legado perdura como uno de los pilares del metal vasco contemporáneo.\n\nEn 2025, el Festival Koba Live de Abadiño anunció una actuación especial de Asgarth como parte de su cartel, marcando un regreso muy esperado por los fans.\n\nEsta participación supone no solo un homenaje a su trayectoria, sino también una celebración de su influencia en la escena metalera vasca, posicionando a Asgarth nuevamente en el centro del panorama musical.`,

  BeforeTheDawn: `Before the Dawn es una banda finlandesa de death metal melódico, formada en 1999 por Tuomas Saukkonen en Nastola.\n\nA lo largo de su carrera, han desarrollado un sonido caracterizado por la combinación de riffs pesados, atmósferas oscuras y melodías melancólicas, consolidándose como una referencia en el género.\n\nTras un receso en 2013, la banda regresó en 2021 con una formación renovada, incluyendo a Paavo Laapotti (voz), Juho Räihä (guitarra) y Pyry Hanski (bajo), además de Saukkonen en la batería.\n\nEn 2023, lanzaron el álbum Stormbringers, seguido por el EP Archaic Flame en marzo de 2024, ambos bajo el sello Napalm Records.\n\nEstos trabajos reflejan una evolución en su sonido, manteniendo la esencia melódica y emocional que los caracteriza, mientras incorporan nuevas influencias y una producción más pulida.\n\nLas letras, introspectivas y cargadas de simbolismo, exploran temas como la pérdida, la resiliencia y la dualidad humana.\n\nEl 20 de septiembre de 2025, Before the Dawn se presentará en la cuarta edición del Festival Koba Live en Abadiño, compartiendo cartel con bandas como Wolfheart y Eclipse.\n\nSu actuación es esperada como uno de los momentos destacados del evento, ofreciendo a los asistentes una experiencia intensa y emotiva que reafirma su posición en la escena del metal melódico.`,

  Eclipse: `Eclipse es una banda sueca de hard rock melódico formada en Estocolmo en 1999, liderada por el vocalista, multiinstrumentista y productor Erik Martensson.\n\nA lo largo de su carrera, han destacado por su energía contagiosa y composiciones que combinan potentes riffs con estribillos pegadizos, consolidándose como una de las principales referencias del hard rock europeo actual.\n\nEn septiembre de 2024, lanzaron su más reciente álbum, Megalomanium II, que ha sido bien recibido por la crítica y los fans.\n\nEste trabajo continúa la línea ascendente de la banda, ofreciendo una mezcla de temas nuevos y la esencia que los caracteriza.\n\nEntre sus canciones más emblemáticas se encuentran “Runaways”, “Roses on Your Grave” y “Viva la Victoria”, que suelen ser puntos culminantes en sus actuaciones en vivo.\n\nEl 20 de septiembre de 2025, Eclipse se presentará en la cuarta edición del Festival Koba Live en Abadiño, compartiendo escenario con bandas como Before The Dawn, Wolfheart y Suicidal Angels.\n\nSu participación en este evento promete ser uno de los momentos destacados del festival, ofreciendo a los asistentes una experiencia vibrante y llena de hard rock de alta calidad.`,

  EhunKilo: `Ehun Kilo es una banda de heavy metal melódico originaria de Elgoibar, Gipuzkoa, formada en 1991.\n\nJunto a Su Ta Gar, fueron pioneros en introducir el euskera en el género del heavy metal, aportando una identidad propia a la escena musical vasca.\n\nSu estilo se caracteriza por una combinación de melodías potentes y riffs pesados, con letras que abordan temas diversos y comprometidos.\n\nDurante su primera etapa, la banda publicó dos álbumes: Euli Artean (1993) y Esaiek... (1995), ambos editados por el sello Oihuka.\n\nEstos trabajos reflejan su sonido distintivo y consolidaron su posición en la escena del metal vasco.\n\nTras disolverse en 1997, Ehun Kilo regresó a los escenarios en 2017 con motivo del 20º aniversario del festival Hatortxu Rock.\n\nDesde entonces, han participado en eventos como el Vértigo Rock en 2022 y compartieron escenario con Su Ta Gar en Eibar en 2023. Diario de un Rockero.\n\nActualmente, la formación está compuesta por Jon Zabala (voz), Jon Iturrino (guitarra), Kristian Etxabe (bajo), Patxi Zabaleta (guitarra) e Iñigo “Fiñi” Barrenetxea (batería).\n\nEl 20 de septiembre de 2025, Ehun Kilo actuará en la cuarta edición del Festival Koba Live en Abadiño, presentando un repertorio lleno de clásicos como “Mendekua”, “Tango Feroz” y “Bihotz Lapurra”, reafirmando su legado en el panorama del metal en euskera.`,

  Moonshinerds: `Moonshinerds es una banda de Durango (Bizkaia) formada en 2009, reconocida por su estilo que fusiona stoner, hard rock, rock melódico y toques de rock clásico.\n\nLa banda está compuesta por Joseba Irigoras (guitarra y voz), Liher Granados (bajo), Jon Sánchez (guitarra) y Antonio Cantero (batería), quien se unió recientemente al grupo.\n\nMoonshinerds se caracteriza por sus composiciones potentes y pegadizas, con un sonido que recuerda a las raíces del rock clásico pero con una energía contemporánea.\n\nSu propuesta ha sido bien recibida en la escena local, destacando por su autenticidad y pasión en el escenario.\n\nEl 20 de septiembre de 2025, Moonshinerds formará parte del cartel del festival Koba Live IV en Abadiño, Bizkaia.\n\nEste evento reunirá a destacadas bandas internacionales y nacionales, como Eclipse, Wolfheart, Suicidal Angels, Before The Dawn, Asgarth y Ehun Kilo.\n\nLa participación de Moonshinerds en este festival representa una oportunidad significativa para la banda de compartir su música con un público más amplio y consolidar su presencia en la escena del rock y metal.\n\nLa actuación promete ser una muestra de su energía y talento, contribuyendo al éxito de esta edición del Koba Live.`,

  TheElectricAlley: `The Electric Alley es una banda de hard rock originaria de Cádiz, España, formada en 2012.\n\nInfluenciados por el rock de los años 70 y 80, su sonido fusiona elementos de bandas legendarias como Led Zeppelin, Aerosmith, y The Black Crowes, creando un estilo propio que destaca por su energía, riffs poderosos y una vocalización cargada de emoción.\n\nDesde su debut con Backward States of Society (2013), la banda ha publicado varios álbumes aclamados, como Get Electrified! (2015), Turning Wheels (2018) y Apache (2022).\n\nEstos trabajos les han permitido consolidarse como una de las propuestas más destacadas dentro del hard rock español.\n\nA lo largo de su carrera, The Electric Alley ha recorrido numerosos escenarios en España y Europa, participando en festivales de gran prestigio como el Z! Live Rock Fest y Raismes Fest, y compartiendo escenario con bandas como The Hellacopters y The Quireboys.\n\nSu enérgico directo, caracterizado por una gran presencia escénica y una química especial con el público, ha sido uno de los factores que les ha permitido ganar una base de seguidores fieles.\n\nEl 20 de septiembre de 2025, The Electric Alley será parte del cartel del Festival Koba Live 2025 en Abadiño, Bizkaia, donde ofrecerán una actuación llena de pasión y rock de alta calidad.`,

  Wolfheart: `Wolfheart es una banda finlandesa de death metal melódico formada en 2013 por Tuomas Saukkonen, conocido por su trabajo en Before the Dawn y Black Sun Aeon.\n\nCon sede en Lahti, Wolfheart combina riffs pesados con atmósferas melódicas y líricas inspiradas en la naturaleza y el invierno finlandés.\n\nHan lanzado siete álbumes de estudio, siendo Draconian Darkness (2024) su más reciente trabajo, publicado bajo el sello Reigning Phoenix Music.\n\nEn noviembre de 2024, Wolfheart se convirtió en la primera banda europea de heavy metal en actuar en Arabia Saudita.\n\nEn septiembre de 2025, la banda participará en la cuarta edición del Festival Koba Live en Abadiño, Bizkaia, junto a otras destacadas formaciones como Suicidal Angels, Eclipse, Before the Dawn, The Electric Alley y Ehun Kilo.\n\nSu actuación promete ser una experiencia intensa que sumergirá al público en su característico estilo de death metal melódico.`
}

export default resumenesBandas
